---
title: "analises_inferenciais"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(ggrepel)
library(rstatix)
```

```{r}

df <- read.csv("dados-limpo.csv")

```

```{r}
#teste t da proporção entre homens e mulheres em cada nível de atenção

tabela_qui_nivel <- table(df$genero, df$nivel_atencao)

result_qui_niveis <- print(chisq.test(tabela_qui_nivel))

result_qui_niveis$stdres


```

```{r}
##teste t da proporção entre homens e mulheres em cada região

tabela_qui_regiao <- table(df$genero, df$regiao)

result_qui_regiao <- chisq.test(tabela_qui_regiao)

result_qui_regiao$stdres
  

```

```{r}
#variável de proporção: "nº de habitantes por profissional de psicologia"
 
df_prop <- df |>
  group_by(nome_do_municipio, regiao, estado) |> 
  summarise(
    populacao_muni = first(populacao_muni), 
    # n() agora contará corretamente centenas ou milhares de linhas para SP
    quanti_psis_muni = n(), 
    prop_psi_muni =  populacao_muni/quanti_psis_muni,
    .groups = 'drop'
  ) |>
  ungroup()

```


```{r}

# verificando pressuposto da proporção 

df_prop |>
  group_by(regiao) |>
  shapiro_test(prop_psi_muni)

levene_test(prop_psi_muni ~ regiao, data = df_prop)

## aqui deu erro, porque a amostra é muito grande

df_prop |>
  group_by(estado) |>
  shapiro_test(prop_psi_muni)

levene_test(prop_psi_muni ~ estado, data = df_prop)
```

```{r}

#anova entre regiões (proporção por região)

##-> os pressupostos não foram acatados. precisa refazer anova

modelo_regiao <- aov(prop_psi_muni ~ regiao, data = df_prop)

summary(modelo_regiao)

TukeyHSD(modelo_regiao)

```


```{r}
#anova entre estados

modelo_estado <- aov(prop_psi_muni ~ estado, data = df_prop)

summary(modelo_estado)

TukeyHSD(modelo_estado)
  
```

```{r}
#correlação entre população e nº de vínculos

## --> que função usar pra verificar os pressupostos?

cor.test(df_prop$populacao_muni, df_prop$quanti_psis_muni, method = "pearson")

```

```{r}
library(ggplot2)

ggplot(df_prop, aes(x = populacao_muni, y = quanti_psis_muni)) +
  geom_point(alpha = 0.6, color = "black") +
  geom_smooth(method = "lm", se = FALSE, color = "gray") + 
  geom_text_repel(
    data = df_prop |> slice_max(populacao_muni, n = 5),
    aes(label = nome_do_municipio), 
    size = 3, 
    box.padding = 0.5, 
    point.padding = 0.5,
    color = "black",
    max.overlaps = Inf) +labs(
    title = "Correlação entre População e Psicólogos",
    x = "População do Município",
    y = "Vínculos de Psicólogos)"
  ) +
  theme_minimal()
```
```

